/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Controller.cadastroController;
import controledeatletas.enderecoClass;
import javax.swing.JOptionPane;

/**
 *
 * @author Kleber Moreira
 */
public class Endereco extends javax.swing.JFrame {

    private telaCadastro telaAnterior;
    /**
     * Creates new form Endereco
     */
    private Endereco() {
        initComponents();
        
        setSize(1280, 852);
    }

    public Endereco(telaCadastro telaAnterior){
        
        this();
        this.telaAnterior = telaAnterior; 
    }
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfPaís = new javax.swing.JTextField();
        tfCep = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENDEREÇO DO ATLETA");
        setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Logradouro:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 30, 110, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Número:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 90, 80, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Complemento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 160, 130, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Bairro:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 220, 80, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("CEP:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 490, 100, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("País:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 430, 70, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cidade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 300, 110, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 370, 90, 22);
        getContentPane().add(tfLogradouro);
        tfLogradouro.setBounds(210, 30, 590, 20);
        getContentPane().add(tfNumero);
        tfNumero.setBounds(210, 90, 110, 20);
        getContentPane().add(tfComplemento);
        tfComplemento.setBounds(210, 160, 590, 20);
        getContentPane().add(tfCidade);
        tfCidade.setBounds(210, 300, 490, 20);
        getContentPane().add(tfBairro);
        tfBairro.setBounds(210, 220, 490, 20);
        getContentPane().add(tfPaís);
        tfPaís.setBounds(210, 430, 250, 20);
        getContentPane().add(tfCep);
        tfCep.setBounds(210, 490, 250, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR ", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 370, 50, 20);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(420, 550, 120, 30);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(620, 550, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kleber Moreira\\Desktop\\Paris_at_sunset_with_the_Eiffel_Tower.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 852);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //Salvando os dados
        String logradouro = tfLogradouro.getText();
        String numero = tfNumero.getText();
        String complemento = tfComplemento.getText();
        String bairro = tfBairro.getText();
        String cidade = tfCidade.getText();
        String país = tfPaís.getText();
        String cep = tfCep.getText();
        
        int Numero;
        int Cep;
        
        try {
        Numero = Integer.parseInt(numero);    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite corretamente o numero da residencia");
            return;
        }
        
        try {
            Cep = Integer.parseInt(cep);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! Digite o cep corretamente");
            return;
        }
        
        enderecoClass endereco = new enderecoClass(logradouro, numero, complemento, bairro, cidade, país, cep);
        
        cadastroController cadastrar = new cadastroController();
        
        cadastrar.cadastrarEndereco(endereco);
        
        if(cadastrar.cadastrarEndereco(endereco))
        {
            JOptionPane.showMessageDialog(this, "Endereco cadastrado com sucesso");
            
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this, "Erro. Todos os dados precisão serem preenchidos corretamente");
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
        telaAnterior.setEnabled(true);
        telaAnterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Endereco().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPaís;
    // End of variables declaration//GEN-END:variables
}
