/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Controller.cadastroController;
import controledeatletas.Atleta;
import javax.swing.JOptionPane;

/**
 *
 * @author Kleber Moreira
 */
public class informacoesGerais extends javax.swing.JFrame {

    
    private telaCadastro telaAnterior;
    /**
     * Creates new form informacoesGerais
     */
    public informacoesGerais() {
        initComponents();
        
        setSize(1124, 550);
    }

    public informacoesGerais(telaCadastro telaAnterior)
    {
        this();
        
        this.telaAnterior = telaAnterior;
    }
                    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfdataNascimento = new javax.swing.JTextField();
        tfAltura = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        tfnomePai = new javax.swing.JTextField();
        tfnomeMae = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfCPF = new javax.swing.JTextField();
        tfRG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfTelefones = new javax.swing.JTextArea();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INFORMAÇÕES GERAIS DO ATLETA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 60, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Data de nascimento: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 70, 120, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 120, 34, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Nome do pai:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 170, 100, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("CPF:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 310, 50, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Telefones:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 360, 70, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Altura:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 60, 50, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Peso:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(660, 70, 60, 14);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Nome da mãe:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 220, 100, 17);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("RG:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 270, 30, 17);
        getContentPane().add(tfNome);
        tfNome.setBounds(240, 30, 670, 20);
        getContentPane().add(tfdataNascimento);
        tfdataNascimento.setBounds(240, 70, 180, 20);
        getContentPane().add(tfAltura);
        tfAltura.setBounds(520, 70, 100, 20);
        getContentPane().add(tfPeso);
        tfPeso.setBounds(700, 70, 100, 20);
        getContentPane().add(tfnomePai);
        tfnomePai.setBounds(240, 170, 670, 20);
        getContentPane().add(tfnomeMae);
        tfnomeMae.setBounds(240, 220, 670, 20);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masculino", "feminino" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 120, 100, 23);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 350, 60, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("-");
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 395, 60, 50);
        getContentPane().add(tfCPF);
        tfCPF.setBounds(240, 310, 260, 20);
        getContentPane().add(tfRG);
        tfRG.setBounds(240, 270, 230, 20);

        tfTelefones.setColumns(20);
        tfTelefones.setRows(5);
        jScrollPane1.setViewportView(tfTelefones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 350, 470, 96);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(570, 460, 100, 30);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(360, 460, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kleber Moreira\\Desktop\\jogador-de-futebol-que-faz-um-tiro-da-bicicleta-2055596.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1110, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //Salvando os dados
        String nome = tfNome.getText();
        String nomeMae = tfnomeMae.getText();
        String nomePai = tfnomePai.getText();
        String CPF = tfCPF.getText();
        String RG = tfRG.getText();
        String dataNascimento = tfdataNascimento.getText();
        String peso = tfPeso.getText();
        String altura = tfAltura.getText();
        
        int cpf;
        int rg;
        int data;
        float Peso = 0.0f;
        float Altura = 0.0f;
        
        try {
        cpf = Integer.parseInt(CPF);    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite corretamente o CPF");
            return;
        }
        
        try {
        rg = Integer.parseInt(RG);    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite corretamente o RG");
            return;
        }
        
        try {
        data = Integer.parseInt(dataNascimento);    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite corretamente a data de nascimento");
            return;
        }
        
        try {
        Peso = Float.parseFloat(peso);    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite corretamente o peso do atleta");
            return;
        }
        
        try {
        Altura = Float.parseFloat(altura);    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite corretamente a altura do atleta");
            return;
        }
        //Criando um objeto atleta
        Atleta atleta = new Atleta(nome, dataNascimento, altura, peso, nomePai, nomeMae, RG, CPF);
        
        cadastroController cadastro = new cadastroController();
        
        cadastro.cadastrarAtleta(atleta);
        
        
        if(cadastro.cadastrarAtleta(atleta))
        {
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
            
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this, "Erro. Campos precisão ser preenchidos corretamente!!!");       
    }//GEN-LAST:event_btSalvarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        // TODO add your handling code here:
        
        telaAnterior.setVisible(true);
        telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setEnabled(false);
        new Telefones(this).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacoesGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacoesGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacoesGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacoesGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacoesGerais().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfRG;
    private javax.swing.JTextArea tfTelefones;
    private javax.swing.JTextField tfdataNascimento;
    private javax.swing.JTextField tfnomeMae;
    private javax.swing.JTextField tfnomePai;
    // End of variables declaration//GEN-END:variables
}
