/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.LinkedList;

/**
 *
 * @author Kleber Moreira
 */
public class telaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();
        
        setSize(1040, 788);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alsways
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstFutebolistas = new LinkedList();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        btInfo = new javax.swing.JButton();
        btEndereco = new javax.swing.JButton();
        btFichaTecnica = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO DO FUTEBOLISTA");
        getContentPane().setLayout(null);

        btAdicionar.setText("Adicionar");
        btAdicionar.setToolTipText("Adicionar um novo jogador");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdicionar);
        btAdicionar.setBounds(0, 0, 100, 40);

        btEditar.setText("Editar");
        btEditar.setToolTipText("Editar um novo jogador");
        btEditar.setEnabled(false);
        getContentPane().add(btEditar);
        btEditar.setBounds(100, 0, 110, 40);

        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Excluir o atleta");
        btExcluir.setEnabled(false);
        getContentPane().add(btExcluir);
        btExcluir.setBounds(330, 0, 110, 40);

        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Salvar o cadastro");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(810, 0, 110, 40);

        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("Cancelar o cadastro");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(920, 0, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista dos jogadores de futebol cadastrados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 160, 400, 30);

        btPesquisar.setText("Relatório");
        btPesquisar.setToolTipText("Pesquisar na lista de jogadores");
        btPesquisar.setEnabled(false);
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(210, 0, 120, 40);

        btInfo.setText("Informações gerais");
        btInfo.setEnabled(false);
        btInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btInfo);
        btInfo.setBounds(280, 80, 160, 50);

        btEndereco.setText("Endereço");
        btEndereco.setEnabled(false);
        btEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(btEndereco);
        btEndereco.setBounds(440, 80, 150, 50);

        btFichaTecnica.setText("Ficha técnica");
        btFichaTecnica.setEnabled(false);
        btFichaTecnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFichaTecnicaActionPerformed(evt);
            }
        });
        getContentPane().add(btFichaTecnica);
        btFichaTecnica.setBounds(590, 80, 140, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "RG", "CPF", "Categoria", "Posição", "Clube"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(290, 210, 452, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kleber Moreira\\Desktop\\nas-jogadores-de-futebol-nuvens-papel-parede-80674.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFichaTecnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFichaTecnicaActionPerformed
        // Chamar a tela de ficha técnica
        setEnabled(false);
        
        new fichaTecnica(this).setVisible(true);
    }//GEN-LAST:event_btFichaTecnicaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();

    }//GEN-LAST:event_btCancelarActionPerformed

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoActionPerformed
        // TODO add your handling code here:
        
        this.setEnabled(false);
        
        new informacoesGerais(this).setVisible(true);
        
        
    }//GEN-LAST:event_btInfoActionPerformed

    private void btEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnderecoActionPerformed
        // TODO add your handling code here:
        
        setEnabled(false);
        
        new Endereco(this).setVisible(true);
        
    }//GEN-LAST:event_btEnderecoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:       
        btEditar.setEnabled(true);
        btExcluir.setEnabled(true);
        btPesquisar.setEnabled(true);
        btInfo.setEnabled(true);
        btEndereco.setEnabled(true);
        btFichaTecnica.setEnabled(true);
        btSalvar.setEnabled(true);
        btCancelar.setEnabled(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEndereco;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFichaTecnica;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.util.List lstFutebolistas;
    // End of variables declaration//GEN-END:variables
}
