/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Controller.cadastroController;
import controledeatletas.Numeros;
import javax.swing.JOptionPane;

/**
 *
 * @author Kleber Moreira
 */
public class Telefones extends javax.swing.JFrame {

    private informacoesGerais telaAnterior;
    
    /**
     * Creates new form Telefones
     */
    private Telefones() {
        initComponents();
        
        setSize(815, 693);
    }

    public Telefones(informacoesGerais telaAnterior)
    {
        this();
        
        this.telaAnterior = telaAnterior;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONTATO");
        setPreferredSize(new java.awt.Dimension(815, 663));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Telefone:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 150, 240, 180);
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(180, 230, 580, 30);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdicionar);
        btAdicionar.setBounds(140, 380, 180, 50);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(460, 380, 170, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kleber Moreira\\Desktop\\celulares2.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(4, 0, 1010, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed

        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        
        String numero = tfTelefone.getText( );
        
        int Numero;
        
        try {
            Numero = Integer.parseInt(numero);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro. Digite o numero de telefone correto");
            return;
        }
        
        Numeros contato = new Numeros(numero);
        
        cadastroController cadastrar = new cadastroController();
        
        cadastrar.cadastrarNumero(contato);
        
        if(cadastrar.cadastrarNumero(contato))
        {
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
            
            this.dispose();
        }
            
        else
            JOptionPane.showMessageDialog(this, "Dados incorretos");
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    telaAnterior.setVisible(true);
    telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telefones().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
